INSERT INTO Coordinadores (nombre_coordinador, apellidos_coordinador, extension_coordinador, mail_coordinador, horario, id_supervisor) 
VALUES
-- Agentes de Supervisores 1 y 2 (Horario: Mañana)
('Ana', 'Mendoza López', 5301, 'amendozalopez1@towing.cr', 'Mañana', 1),
('Luis', 'García Rojas', 5302, 'lgarciarojas2@towing.cr', 'Mañana', 1),
('María', 'Fernández Castro', 5303, 'mfernandezcastro3@towing.cr', 'Mañana', 1),
('Pedro', 'Sánchez Mora', 5304, 'psanchezmora4@towing.cr', 'Mañana', 1),
('Carmen', 'Ramírez Vargas', 5305, 'cramirezvargas5@towing.cr', 'Mañana', 1),
('Jorge', 'Torres Navarro', 5306, 'jtorresnavarro6@towing.cr', 'Mañana', 1),
('Elena', 'Díaz Cordero', 5307, 'ediazcordero7@towing.cr', 'Mañana', 1),
('Diego', 'Herrera Guzmán', 5308, 'dherreraguzman8@towing.cr', 'Mañana', 1),
('Lucía', 'Ríos Campos', 5309, 'lrioscampos9@towing.cr', 'Mañana', 1),
('Andrés', 'Salazar Méndez', 5310, 'asalazarmendez10@towing.cr', 'Mañana', 1),

('Valeria', 'Chaves Solís', 5311, 'vchavessolis11@towing.cr', 'Mañana', 2),
('Raúl', 'Vargas Cruz', 5312, 'rvargascruz12@towing.cr', 'Mañana', 2),
('Isabel', 'Paredes Rivas', 5313, 'iparedesrivas13@towing.cr', 'Mañana', 2),
('Fernando', 'Castro León', 5314, 'fcastroleon14@towing.cr', 'Mañana', 2),
('Gabriela', 'Mora Reyes', 5315, 'gmorareyes15@towing.cr', 'Mañana', 2),
('Hugo', 'Jiménez Soto', 5316, 'hjimenezsoto16@towing.cr', 'Mañana', 2),
('Adriana', 'Luna Fuentes', 5317, 'alunafuentes17@towing.cr', 'Mañana', 2),
('Martín', 'Silva Mendoza', 5318, 'msilvamendoza18@towing.cr', 'Mañana', 2),
('Patricia', 'Navarro Ortiz', 5319, 'pnavarroortiz19@towing.cr', 'Mañana', 2),
('Sergio', 'Ortega Peña', 5320, 'sortegapeña20@towing.cr', 'Mañana', 2),

-- Agentes de Supervisores 3 y 4 (Horario: Tarde)
('Camila', 'Delgado Ríos', 5321, 'cdelgadorios21@towing.cr', 'Tarde', 3),
('Roberto', 'Cortés Herrera', 5322, 'rcortesherrera22@towing.cr', 'Tarde', 3),
('Daniela', 'Vega Paredes', 5323, 'dvegaparedes23@towing.cr', 'Tarde', 3),
('Javier', 'Aguilar Mora', 5324, 'jaguilarmora24@towing.cr', 'Tarde', 3),
('Renata', 'Flores Castro', 5325, 'rflorescastro25@towing.cr', 'Tarde', 3),
('Óscar', 'Miranda López', 5326, 'omirandalopez26@towing.cr', 'Tarde', 3),
('Paulina', 'Santana Díaz', 5327, 'psantanadiaz27@towing.cr', 'Tarde', 3),
('Ricardo', 'Rojas García', 5328, 'rrojasgarcia28@towing.cr', 'Tarde', 3),
('Ximena', 'Guerrero Soto', 5329, 'xguerrerosoto29@towing.cr', 'Tarde', 3),
('Felipe', 'Cordero Navarro', 5330, 'fcorderonavarro30@towing.cr', 'Tarde', 3),

('Alejandro', 'Méndez Campos', 5331, 'amendezcampos31@towing.cr', 'Tarde', 4),
('Mariana', 'Soto Vargas', 5332, 'msotovargas32@towing.cr', 'Tarde', 4),
('Gustavo', 'León Ríos', 5333, 'gleonrios33@towing.cr', 'Tarde', 4),
('Verónica', 'Paz Herrera', 5334, 'vpazherrera34@towing.cr', 'Tarde', 4),
('Emilio', 'Fuentes Luna', 5335, 'efuentesluna35@towing.cr', 'Tarde', 4),
('Natalia', 'Reyes Ortega', 5336, 'nreyesortega36@towing.cr', 'Tarde', 4),
('Rodrigo', 'Camacho Silva', 5337, 'rcamachosilva37@towing.cr', 'Tarde', 4),
('Carolina', 'Orozco Mendoza', 5338, 'corozcomendoza38@towing.cr', 'Tarde', 4),
('Arturo', 'Peña Delgado', 5339, 'apeñadelgado39@towing.cr', 'Tarde', 4),
('Alicia', 'Cruz Cortés', 5340, 'acruzcortes40@towing.cr', 'Tarde', 4),

-- Agentes de Supervisores 5 y 6 (Horario: Noche)
('Héctor', 'Morales Vega', 5341, 'hmoralesvega41@towing.cr', 'Noche', 5),
('Rosa', 'Guzmán Aguilar', 5342, 'rguzmanaguilar42@towing.cr', 'Noche', 5),
('Manuel', 'Solis Flores', 5343, 'msolislores43@towing.cr', 'Noche', 5),
('Teresa', 'Ortiz Miranda', 5344, 'tortizmiranda44@towing.cr', 'Noche', 5),
('Francisco', 'Duran Santana', 5345, 'fduransantana45@towing.cr', 'Noche', 5),
('Beatriz', 'Vázquez Rojas', 5346, 'bvazquezrojas46@towing.cr', 'Noche', 5),
('José', 'Serrano Guerrero', 5347, 'jserranoguerrero47@towing.cr', 'Noche', 5),
('Lorena', 'Montes Paz', 5348, 'lmontespaz48@towing.cr', 'Noche', 5),
('Alberto', 'Rosales Fuentes', 5349, 'arosalesfuentes49@towing.cr', 'Noche', 5),
('Mónica', 'Espinoza Reyes', 5350, 'mespinozareyes50@towing.cr', 'Noche', 5),

('Raquel', 'Maldonado Camacho', 5351, 'rmaldonadocamacho51@towing.cr', 'Noche', 6),
('Guillermo', 'Valverde Orozco', 5352, 'gvalverdeorozco52@towing.cr', 'Noche', 6),
('Silvia', 'Cervantes Montes', 5353, 'scervantesmontes53@towing.cr', 'Noche', 6),
('Enrique', 'Rangel Cruz', 5354, 'erangelcruz54@towing.cr', 'Noche', 6),
('Claudia', 'Juárez Montes', 5355, 'cjuarezmontes55@towing.cr', 'Noche', 6),
('Pablo', 'Núñez Rosales', 5356, 'pnunezrosales56@towing.cr', 'Noche', 6),
('Irene', 'Medina Espinoza', 5357, 'imedinaespinoza57@towing.cr', 'Noche', 6),
('Alfonso', 'Espinoza Cruz', 5358, 'aespinozacruz@towing.cr', 'Noche', 6),
('Esther', 'Tapia Valverde', 5359, 'etapiavalverde59@towing.cr', 'Noche', 6),
('Joaquín', 'Espinoza Cervantes', 5360, 'jespinozacervantes@towing.cr', 'Noche', 6) 
